### ISSUE TITLE
نحوه نصب اسکریپت  در مرزبان؟

### ISSUE THREAD

**Issue by HamidKing7** [masoudgb/Gost-ip6#1]
بابت اسکریپت عالی تون سپاس گزارم برای نصب روی مرزبان چکاری باید انجام داد؟
من الان سرور مستر مرزبان رو دارم بعلاوه سرور نود که هردو خارج هستن
الان بخوام این اسکریپت رو نصب بکنم
یک سرور ایران تهیه کنم که ipv6 باشه اونو باید نود بکنم به سرور مستر؟

**Comment by masoudgb** [comment]
سپاسگزارم از محبتتون 🌹
فقط کافیه اسکریپت در سرور ایران اجرا بشه البته در نظر داشته باشید سرور ایران و خارج هردو باید از ایپی 6 پشتیبانی کنند در این صورت کل ترافیک از طریق گاست از سرور ایران به سرور خارج شما منتقل میشه تفاوتی در ارسال ترافیک به پنل مرزبان و یا ایکس یو ای وجود ندارد
