### ISSUE TITLE
خطا

### ISSUE THREAD

**Issue by hamed141512** [masoudgb/Gost-ip6#10]
آخرش این خطا هارو میده :

ost downloaded successfully.
LICENSE
README.md
README_en.md
gost
Gost installed successfully.
tee: /usr/lib/systemd/system/gost.service: No such file or directory
Do you want to add another destination IP? (y/n): n
tee: /usr/lib/systemd/system/gost.service: No such file or directory
tee: /usr/lib/systemd/system/gost.service: No such file or directory
Failed to enable unit: Unit file gost.service does not exist.
Failed to restart gost.service: Unit gost.service not found.

**Comment by masoudgb** [comment]
درود وقت بخیر
اسکریپت موفق به ایجاد فایل گوست سرویس نشده است
مسائل زیادی میتواند این مشکل را ایجاد کند مانند استفاده از اسکریپت های دیگر در سرور ویا سیستم عامل های خاص که توصیه من استفاده از ابونتو ورژن 20.04 است ویا محدودیتهای اعمال شده در سرور از سمت شما و دلایل دیگر
لطفاً اطلاعات بیشتری از سرور خود ارائه دهید

**Comment by hamed141512** [comment]
فقط اسکریپت x-ui روش نصب هست و پورت 443 رو فوروارد کردم به یجای دیگه.
ورژن ابونتو 18 هست
