### ISSUE TITLE
سوال

### ISSUE THREAD

**Issue by NotMRGH** [masoudgb/Gost-ip6#11]
اگه زیر ساخت اینترنت ایران خوب باشه آیپی خارج هم تمیز باشه اختلال که نداره با 50 تا 100 تا یوزر و آیپی فیلتر نمیشه ؟

**Comment by masoudgb** [comment]
درود وقت بخیر 
مشکلی وجود ندارد در ضمن اگر ایپی 4 سرور خارج فیلتر باشد میتوانید از ایپی 6 بدون مشکل استفاده بفرمایید
