### ISSUE TITLE
مشکل

### ISSUE THREAD

**Issue by Mahdi84S** [masoudgb/Gost-ip6#12]
درود
هنوز هم رنج آیپی ipv6 کار نمیکنه

**Comment by masoudgb** [comment]
درود وقت بخیر آیا ایپی رنج را با کاما وارد میکنید، در ضمن توجه بفرمایید وقتی از رنج ایپی رنج استفاده میکنید مجموع تعداد ایپی از 30.000 تجاوز نکند
البته این محدودیت در آپدیت بعدی رفع خواهد شد

**Comment by masoudgb** [comment]
> فکر کنم بخاطر محدودیت پورت باشد چون من در اسکریپیت ( 23,65535 ) رنج پورت میزنم

درود وقت بخیر
در حال حاضر امکان فوروارد بیش از 30.000 پورت نیست
شما میتوانید 23,30023 فوروارد کنید
با احترام 🌹

**Comment by Mahdi84S** [comment]
شما میتوانید یک اسکریپت اختصاصی برای من درست کنید که محدودیت پورت نداشته باشه و با ipv6 کار کنه ، اختلال نداشته باشه ، پایدار باشه و سرعتش خوب باشه؟
هزینش هم میدم فقط قبلش بگید هزینش چقدر میشه؟

**Comment by masoudgb** [comment]
> شما میتوانید یک اسکریپت تانل اختصاصی برای من درست کنید که محدودیت پورت نداشته باشه و با ipv6 کار کنه ، اختلال نداشته باشه ، پایدار باشه و سرعتش خوب باشه؟ هزینش هم میدم فقط قبلش بگید هزینش چقدر میشه؟

امیدوارم این اسکریپت در آپدیت های بعدی خواسته های شمارو برآورده کنه 
نیاز به هزینه نیست در حد توان به توسعه اسکریپت خواهم پرداخت و خدمت شما و باقی دوستان ارایه میکنم با احترام 🌹

**Comment by Mahdi84S** [comment]
ممنون از شما🙏🏻
چون آخه کارم گیر هستش گفتم
