### ISSUE TITLE
rangport

### ISSUE THREAD

**Issue by pjalil74** [masoudgb/Gost-ip6#13]
سلام استاد قسمت rangport ایرادی داره یا تا چه عددی کار میکنه ؟

**Comment by masoudgb** [comment]
درود دوست عزیزم
هر رنجی رو میتونین انتخاب کنین فقط بیش از 30.000 ایپی نشه

**Comment by pjalil74** [comment]
ممنون استاد منظورتون بیشتر از 30.000 پورت نشه درسته ؟

**Comment by masoudgb** [comment]
بله دقیقا دوست من

**Comment by pjalil74** [comment]
مرسی  استاد ممنون منتظر اپدیت ها خفنتون هستیم و یه سوال دیگه اگه سرور ریبوت شه خودکار اجرا میشه دستور ؟

**Comment by masoudgb** [comment]
ممنون از شما دوست عزیزم 🌹
بله خودکار اجرا میشه

**Comment by mr-mr7** [comment]
استاد من رنج ایپی رو هر جوری امتحان میکنم جواب نمیده
و یه مشکلی هم که هست وقتی uninstall میزنم که کامل حذف بشه ودوباره نصبش کنم تانل هنوز موجوده و حذف نشده
ممنون ازتون بابت اسکریپ عالیتون

**Comment by masoudgb** [comment]
> استاد من رنج ایپی رو هر جوری امتحان میکنم جواب نمیده و یه مشکلی هم که هست وقتی uninstall میزنم که کامل حذف بشه ودوباره نصبش کنم تانل هنوز موجوده و حذف نشده ممنون ازتون بابت اسکریپ عالیتون

سپاسگزارم دوست عزیزم 🌹
از چه سیستم عاملی استفاده میکنید، چه رنجی وارد فرمودید، آیا از کاما برای جدا کردن ابتدا و انتهای رنج استفاده فرمودید، چه قسمتی از اسکریپت بعد از لغو نصب باقی مونده و آیا خطایی دریافت کردید

**Comment by mr-mr7** [comment]
ابونتو 22.04
30000,60000
یه کاما فقط وسط رنج گذاشتم
وقتی حذف رو زدم هنوزم کانفیگم جواب میداد

**Comment by masoudgb** [comment]
از آخرین نسخه موجود در گیت استفاده فرمودید.؟

**Comment by mr-mr7** [comment]
ازا ین پکیج استفاده کردم
 bash <(curl -Ls https://github.com/masoudgb/Gost-ip6/raw/main/Gost.sh)

**Comment by masoudgb** [comment]
مشکلاتی که فرمودید قبلاً وجود داشت که در آپدیت کاملا رفع شده از رنج 54,65000 هم میتونید استفاده بفرمایید 
لطفاً با ابونتو 20.04 تست بفرمایید نتیجه رو ارسال بفرمایید

**Comment by mr-mr7** [comment]
باشه چشم
ممنون

**Comment by mr-mr7** [comment]
از ورژن معمولی استفاده کنم یا کاستوم شده؟
و فرقشون چیه؟

**Comment by masoudgb** [comment]
از لینک اول کلون استفاده بفرمایید 
کاستوم مخصوص نسخه های قبلی است

**Comment by mr-mr7** [comment]
با ابونتو 20.04 هم امتحان کردم
رنج رو گذاشتم روی 
56,65000
ولی یه سری پورت ها جواب میده یه سری ن
همه پورت هارو پشتیبانی نمیکنه

**Comment by masoudgb** [comment]
رنج رو برای مثال عرض کردم هر عددی بین 54 تا 65000 میتونین انتخاب کنید
آیا روی سرور اسکریپت دیگه ای دارید
آیا از فایروال استفاده کردید

**Comment by mr-mr7** [comment]
سرور خام بود گرفتم
یه اسکریپت برای تولید private ip نصب کردم روش که از این گیت هاب بود
https://github.com/Azumi67/PrivateIP_TCP-UDP_Tunnel
و چیز دیگه ای هم نصب نکردم
من کل رنج رو زدم که مشکل پورت نداشته باشه

**Comment by masoudgb** [comment]
اسکریپتی که فرمودید مشکل رو ایجاد کرده اگر ایپی 6 نیاز هست از دیتاسنتری بگیرید که از ایپی 6 پشتیبانی کنه

**Comment by mr-mr7** [comment]
ممنون بابت پاسخگویی
