### ISSUE TITLE
Range Ports

### ISSUE THREAD

**Issue by alex-comix** [masoudgb/Gost-ip6#14]
با سلام لطفا امکانش هست رنج پورت رو کامل بازکنید چون یوزرهای پنل های قبلی ما به صورت رندوم ساخته شدن یعنی از 1700 بگیر تا 65530 ! خیلی مشکل که بخوایم روی چنتا پورت خاص در حال حاضر سوییچ کنیم .. کامل باز بشه عالی میشه الان وقتی روی رنج پورت میزنم از 23,65535 نصب کنه نگاه میکنم از 39367 میخونه تا 65535 خواهشا از مالتی پورت کامل نصب بشه منابع سرور کاملا کشش داره خیالتون راحت مرسی

**Comment by masoudgb** [comment]
سلام در آپدیت بعدی حتما لحاظ میشه
