### ISSUE TITLE
نسخه GOST

### ISSUE THREAD

**Issue by alex-comix** [masoudgb/Gost-ip6#15]
با سلام در حال حاضر موقع انتخاب ورژن 3 کدام نسخه NIGHTLY نصب میگردد ؟ آیا مستقیم اخرین نسخه Pre-release نصب می گردد یا نسخه اولیه ؟ چون ورژن در حال حاضر 20240128 که ویژگی و فیکس های بهتری داره تشکر..

**Comment by masoudgb** [comment]
عرض ادب در حال حاظر از آخرین نسخه استفاده شده 
20240128
با احترام
