### ISSUE TITLE
IP

### ISSUE THREAD

**Issue by NotMRGH** [masoudgb/Gost-ip6#16]
سلام وقتتون بخیر ❤️ یه سوال داشتم میشه فقط از IPv6 خارج استفاده کرد چون فقط توی سرور خارج IPV6 دارم توی سرور ایران ipv4 راهی هست ؟

**Comment by masoudgb** [comment]
درود وقت بخیر 🌹
در اینصورت باید برای هر دو سرور ایپی لوکال ایجاد کنید اما این کار باعث افت شدید سرعت ناپایداری و افزایش مصرف ترافیک میشود به همین خاطر توصیه نمیکنم
