### ISSUE TITLE
unable to resolve hos

### ISSUE THREAD

**Issue by BigStarling** [masoudgb/Gost-ip6#17]
سلام من این مشکل رو روی سرور ایرانم دارم و تانل کار نمیکنه
unable to resolve host (server name): Name or service not known
sudo: unable to resolve host (server name): Name or service not known
sudo: unable to resolve host (server name): Name or service not known
sudo: unable to resolve host (server name): Name or service not known
sudo: unable to resolve host (server name): Name or service not known
Gost configuration applied successfully.

**Comment by masoudgb** [comment]
درود وقت بخیر پیش از اجرای اسکریپت 
nano/etc/resolv.conf
سپس nameserver را ویرایش کنید به
nameserver 8.8.8.8
ذخیره کنید و اسکریپت را نصب کنید

> سلام من این مشکل رو روی سرور ایرانم دارم و تانل کار نمیکنه unable to resolve host (server name): Name or service not known sudo: unable to resolve host (server name): Name or service not known sudo: unable to resolve host (server name): Name or service not known sudo: unable to resolve host (server name): Name or service not known sudo: unable to resolve host (server name): Name or service not known Gost configuration applied successfully.

**Comment by BigStarling** [comment]
![Shot 0017](https://github.com/masoudgb/Gost-ip6/assets/123511699/336036d9-7eac-4cf8-8d43-2fc7287c6ed8)
سلام نصب بود از قبل مشکل چیه

**Comment by masoudgb** [comment]
> ![Shot 0017](https://private-user-images.githubusercontent.com/123511699/301950355-336036d9-7eac-4cf8-8d43-2fc7287c6ed8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MDI1NjIsIm5iZiI6MTcwNjkwMjI2MiwicGF0aCI6Ii8xMjM1MTE2OTkvMzAxOTUwMzU1LTMzNjAzNmQ5LTdlYWMtNGNmOC04ZDQzLTJmYzcyODdjNmVkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQxOTMxMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NWUzMGM4YTNlZDQ1OTAzYWE4MmRjMzc0ZTVjNWJiMmZmZWRhZWRmN2JmNzRhMDk1YjZlY2M0YWRjZmJmMjE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2rypEfTmnA4Yg1DwXfxIdjwfa5TSkBO_-LX8RMOxemY) سلام نصب بود از قبل مشکل چیه

خطای شما مستقیم به عدم شناسایی سرور نیم توسط کارت شبکه اشاره دارد
معمولا دی آن اس باعث این مشکل میشه

**Comment by BigStarling** [comment]
الان مشکل از dns ها هست ؟
به صورت دیفالت هم dns ها ست بودن 
اگه مشکل از dns ها هست یعنی من بقیه dns ها به جز 8.8.8.8 رو پاک کنم؟

**Comment by masoudgb** [comment]
گزینه option و search رو کامنت کنید و مجدد بررسی کنید
