### ISSUE TITLE
گوست ورژن 3

### ISSUE THREAD

**Issue by Mohammadaminsdr** [masoudgb/Gost-ip6#2]
سلام ممنون از این اسکریپت خفنتون اگه امکانش هست از گوست ورژن 3 و ریروسش استفاده بشه که خیلی بهتره

**Comment by masoudgb** [comment]
خواهش میکنم محمد عزیز 🌹
گاست 3 در اجرای ایپی 6 مصرف CPU رو بالا برد حتما اگر این مشکل رفع بشه در ابدیت بعدی انجام میشه
