### ISSUE TITLE
مشکل در انتخاب گزینه رنج آی پی

### ISSUE THREAD

**Issue by webadminlist** [masoudgb/Gost-ip6#20]
درود آقا مسعود
ممنونم بابت زحماتی که میکشید
یه مشکلی وجود داره
وقتی رنج آی پی رو انتخاب میکنیم و رنج میدیم تانل کار نمیکنه
میشه راهنمایی کنید چیکار کنیم؟

**Comment by masoudgb** [comment]
> درود آقا مسعود ممنونم بابت زحماتی که میکشید یه مشکلی وجود داره وقتی رنج آی پی رو انتخاب میکنیم و رنج میدیم تانل کار نمیکنه میشه راهنمایی کنید چیکار کنیم؟

درود دوست عزیزم
برای ورودی بیش از 30000 پورت محدودیت وجود داره که در آپدیت بعدی رفع میشه

**Comment by Mahdi84S** [comment]
درود ، وقت بخیر
آپدیت بعدی کی منتشر میشه؟

**Comment by masoudgb** [comment]
> درود ، وقت بخیر آپدیت بعدی کی منتشر میشه؟

وقت بخیر تا پایان هفته جاری

**Comment by webadminlist** [comment]
سپاس از شما
منتظر آپدیت هستیم

**Comment by webadminlist** [comment]
یه پیشنهادی دارم برای برای آپدیت بعدی تو قسمت رنج آی پی
به نظرم یه گزینه ای باشه که همه پورت ها رو فوروارد کنه و وقتی انتخاب میکنیم بپرسه که چه پورتی رو نمیخوای فوروارد کنید، مثلا پورت 22 یا هر پورت دیگه ای رو exclude کنیم

**Comment by masoudgb** [comment]
ممنون از پیشنهادت حتما در نظر میگیرم

**Comment by webadminlist** [comment]
ممنونم از شما

**Comment by webadminlist** [comment]
سلام مجدد آقا مسعود عزیز
تو نسخه جدید رنج آی پی اضافه نشده؟

**Comment by masoudgb** [comment]
> سلام مجدد آقا مسعود عزیز تو نسخه جدید رنج آی پی اضافه نشده؟

سلام دوست عزیزم اضافه شده البته برخی دوستان فرمودند مشکل داره که دارم بررسی میکنم

**Comment by webadminlist** [comment]
من هم رنج پورت رو انتخاب کردم از 1000 تا 70000 هزار
که کار نکرد

**Comment by masoudgb** [comment]
> من هم رنج پورت رو انتخاب کردم از 1000 تا 70000 هزار که کار نکرد

درود وقت بخیر بجای 70000 وارد بفرمایید 65000

**Comment by webadminlist** [comment]
چشم چک میکنم الان اطلاع میدم

**Comment by webadminlist** [comment]
متاسفانه کار نکرد

**Comment by masoudgb** [comment]
> متاسفانه کار نکرد

systemctl start gost_0
systemctl start gost_1
systemctl start gost_2
systemctl start gost_3
systemctl start gost_4
به ترتیب گوست رو استارت بفرمایید 
اگر مشکل رفع نشد با دستور زیر لاگ رو ارسال بفرمایید

systemctl status gost_0

**Comment by webadminlist** [comment]
خدمت شما:
● gost_0.service - GO Simple Tunnel
     Loaded: loaded (/lib/systemd/system/gost_0.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2024-02-11 11:40:40 UTC; 1min 38s ago
   Main PID: 2412
      Tasks: 4 (limit: 1117)
     Memory: 293.1M
     CGroup: /system.slice/gost_0.service

Feb 11 11:42:18 test-sapphire gost[2412]: {"handler":"tcp","kind":"service","level":"info","listener":"tcp","msg":"listen>Feb 11 11:42:18 test-sapphire gost[2412]: {"handler":"tcp","kind":"service","level":"info","listener":"tcp","msg":"listen>Feb 11 11:42:18 test-sapphire gost[2412]: {"handler":"tcp","kind":"service","level":"info","listener":"tcp","msg":"listen>Feb 11 11:42:18 test-sapphire gost[2412]: {"handler":"tcp","kind":"service","level":"info","listener":"tcp","msg":"listen>Feb 11 11:42:18 test-sapphire gost[2412]: {"handler":"tcp","kind":"service","level":"info","listener":"tcp","msg":"listen>Feb 11 11:42:18 test-sapphire gost[2412]: {"handler":"tcp","kind":"service","level":"info","listener":"tcp","msg":"listen>Feb 11 11:42:18 test-sapphire gost[2412]: {"handler":"tcp","kind":"service","level":"info","listener":"tcp","msg":"listen>Feb 11 11:42:18 test-sapphire gost[2412]: {"handler":"tcp","kind":"service","level":"info","listener":"tcp","msg":"listen>Feb 11 11:42:18 test-sapphire gost[2412]: {"handler":"tcp","kind":"service","level":"info","listener":"tcp","msg":"listen>Feb 11 11:42:18 test-sapphire gost[2412]: {"handler":"tcp","kind":"service","level":"info","listener":"tcp","msg":"listen>lines 1-18/18 (END)

**Comment by masoudgb** [comment]
> خدمت شما: ● gost_0.service - GO Simple Tunnel Loaded: loaded (/lib/systemd/system/gost_0.service; enabled; vendor preset: enabled) Active: active (running) since Sun 2024-02-11 11:40:40 UTC; 1min 38s ago Main PID: 2412 Tasks: 4 (limit: 1117) Memory: 293.1M CGroup: /system.slice/gost_0.service
> 
> Feb 11 11:42:18 test-sapphire gost[2412]: {"handler":"tcp","kind":"service","level":"info","listener":"tcp","msg":"listen>Feb 11 11:42:18 test-sapphire gost[2412]: {"handler":"tcp","kind":"service","level":"info","listener":"tcp","msg":"listen>Feb 11 11:42:18 test-sapphire gost[2412]: {"handler":"tcp","kind":"service","level":"info","listener":"tcp","msg":"listen>Feb 11 11:42:18 test-sapphire gost[2412]: {"handler":"tcp","kind":"service","level":"info","listener":"tcp","msg":"listen>Feb 11 11:42:18 test-sapphire gost[2412]: {"handler":"tcp","kind":"service","level":"info","listener":"tcp","msg":"listen>Feb 11 11:42:18 test-sapphire gost[2412]: {"handler":"tcp","kind":"service","level":"info","listener":"tcp","msg":"listen>Feb 11 11:42:18 test-sapphire gost[2412]: {"handler":"tcp","kind":"service","level":"info","listener":"tcp","msg":"listen>Feb 11 11:42:18 test-sapphire gost[2412]: {"handler":"tcp","kind":"service","level":"info","listener":"tcp","msg":"listen>Feb 11 11:42:18 test-sapphire gost[2412]: {"handler":"tcp","kind":"service","level":"info","listener":"tcp","msg":"listen>Feb 11 11:42:18 test-sapphire gost[2412]: {"handler":"tcp","kind":"service","level":"info","listener":"tcp","msg":"listen>lines 1-18/18 (END)

سپاسگزارم مشکلی نیست و گوست ران هستش لطفا تا گوست 4 تست بفرمایید و اگر مشکلی وجود داشت لاگ رو ارسال بفرمایید

**Comment by webadminlist** [comment]
> > متاسفانه کار نکرد
> 
> systemctl start gost_0 systemctl start gost_1 systemctl start gost_2 systemctl start gost_3 systemctl start gost_4 به ترتیب گوست رو استارت بفرمایید اگر مشکل رفع نشد با دستور زیر لاگ رو ارسال بفرمایید
> 
> systemctl status gost_0

هر 4 تا رو زدم
ولی تانل برقرار نشده
و پنل با آی پی ایران بالا نمیاد!

**Comment by masoudgb** [comment]
ایپی خارج رو در ایران پینگ بگیرید

**Comment by webadminlist** [comment]
ipv6 هست

**Comment by webadminlist** [comment]
پورت رو دستی میزنم کار میکنه
رنج پورت میزنم کار نمیکنه

**Comment by webadminlist** [comment]
تا 20 تا پورت رو ب هم میزنم کار میکنه
ولی تو قسمت پورت دستی، بیشتر پورت وارد میکنم مثلا 25 تا دیگه کار نمیکنه
باید تو چند پارت انجام بدیم
مثلا اگه 100 تا پورت داریم
5 تا 20 تا رو بصورت دستی وارد میکنیم
