### ISSUE TITLE
نمایش منو ها بعد از نصب

### ISSUE THREAD

**Issue by mr-mr7** [masoudgb/Gost-ip6#22]
سلام و درود اقا مسعود
اول از همه ممنون بابت زحمتی ک کشیدید
موردی که وجود داشت وقتی Gost نصب شد چطوری دوباره میتونیم منوهارو ببینیم؟
و چطوری میشه کلا حذفش کرد؟
چون من uninstall رو زدم بازم تانل ها موجود بود

**Comment by saeed-Underline** [comment]
run this to see the script again:

```bash
bash <(curl -Ls https://github.com/masoudgb/Gost-ip6/raw/main/Gost.sh)
```

then select 3 option

but even after that still the service is running

you should run this command too

```bash
service gost stop
systemctl daemon-reload
```

**Comment by masoudgb** [comment]
> سلام و درود اقا مسعود اول از همه ممنون بابت زحمتی ک کشیدید موردی که وجود داشت وقتی Gost نصب شد چطوری دوباره میتونیم منوهارو ببینیم؟ و چطوری میشه کلا حذفش کرد؟ چون من uninstall رو زدم بازم تانل ها موجود بود

reboot بفرمایید

**Comment by mr-mr7** [comment]
@masoudgb @saeed-Underline 
ممنون از پاسختون

**Comment by mr-mr7** [comment]
یه سوال دیگه
گزینه range ports مشکلش حل نشد؟
و اینکه add new ip در حال حاضر جواب نمیده؟
چون تست کردم باهاش مشکل داشت و اضافه نشد

**Comment by masoudgb** [comment]
> یه سوال دیگه گزینه range ports مشکلش حل نشد؟ و اینکه add new ip در حال حاضر جواب نمیده؟ چون تست کردم باهاش مشکل داشت و اضافه نشد

سلام متاسفانه سورس آپدیت مشکل داشت موقتا نسخه قبلی جایگزین شد
