### ISSUE TITLE
مشکل در اپراتور رایتل

### ISSUE THREAD

**Issue by FRIBANGI** [masoudgb/Gost-ip6#24]
سلام وقتتون بخیر باشه 
اسکریپت خیلی خوبی هست فقط یه مشکلی که دارم اینکه روی همه اپراتور ها اوکیه ولی روی رایتل بالا نمیاد و مشکل داره بنظرتون مشکل از کجا میتونه باشه

**Comment by masoudgb** [comment]
> سلام وقتتون بخیر باشه اسکریپت خیلی خوبی هست فقط یه مشکلی که دارم اینکه روی همه اپراتور ها اوکیه ولی روی رایتل بالا نمیاد و مشکل داره بنظرتون مشکل از کجا میتونه باشه

درود وقت بخیر بنظر میرسه این مشکل مربوط به سرور ایران باشه، پیشنهاد میکنم با سرور دیگه ای از ایران بررسی کنید
