### ISSUE TITLE
مشکل در نسخه جدید

### ISSUE THREAD

**Issue by Pggamers1** [masoudgb/Gost-ip6#25]
سلام وقتی میخوام نسخه ی جدید رو استفاده کنم و پورت جدید رو میزنم باز کار نمیکنه و مجبورم از نسخه ی 0.6 استفاده کنم میشه بگید باید چیکار کنم تا بتونم از نسخه ی جدید استفاده کنم

**Comment by masoudgb** [comment]
درود وقت بخیر
اسکریپت دیگه ای در سرور نصب کردید.؟

**Comment by Pggamers1** [comment]
خیر فقط همینه

**Comment by masoudgb** [comment]
لطفاً ابونتو 20.04 نصب بفرمایید و نسخه جدید رو تست کنید

**Comment by SoroushImanian** [comment]
> لطفاً ابونتو 20.04 نصب بفرمایید و نسخه جدید رو تست کنید

دقیقا منم این مشکل رو دارم رو سرور اصلیم تست کردم ورژن جدید گوست ۳ تو موقع نصبش ارور Line 111 /fd میده و نمیدونم مشکل از کجاست برای همین رو یک سرور ایران جدید که همون لحظه خریداری کردم و هیچی روش نصب نیست ورژن 22.04 تست کردم هم مشکل داشت اسکریپت ورژن جدید 

ولی موقع نصب ورژن 0.6 رو تست کردم به خوبی کار میکنه ، نمیدونم مشکل از کجاست بهتره یک گزینه بیاد که نشون بده اسکریپت با چه مشخصاتی بالا هست مثلا بگه گوست با تانل tcp با ورژن گوست ۳ بالاست یا ... 

در کل ممنون از شما

   bash <(curl -Ls https://github.com/masoudgb/Gost-ip6/raw/v0.6/Gost.sh)

**Comment by SoroushImanian** [comment]
> لطفاً ابونتو 20.04 نصب بفرمایید و نسخه جدید رو تست کنید

و وقتی اسکریپت جدید رو رو tcp. و گوست ۳ بالا میاوردم گوست بالا میومد سرویسش 
gost_0.service

ولی تونل کار نمیکنه ولی اسکریپت ورژن 0.6 رو تست کردم کار میکنه

**Comment by masoudgb** [comment]
> > لطفاً ابونتو 20.04 نصب بفرمایید و نسخه جدید رو تست کنید
> 
> دقیقا منم این مشکل رو دارم رو سرور اصلیم تست کردم ورژن جدید گوست ۳ تو موقع نصبش ارور Line 111 /fd میده و نمیدونم مشکل از کجاست برای همین رو یک سرور ایران جدید که همون لحظه خریداری کردم و هیچی روش نصب نیست ورژن 22.04 تست کردم هم مشکل داشت اسکریپت ورژن جدید
> 
> ولی موقع نصب ورژن 0.6 رو تست کردم به خوبی کار میکنه ، نمیدونم مشکل از کجاست بهتره یک گزینه بیاد که نشون بده اسکریپت با چه مشخصاتی بالا هست مثلا بگه گوست با تانل tcp با ورژن گوست ۳ بالاست یا ...
> 
> در کل ممنون از شما
> 
> bash <(curl -Ls https://github.com/masoudgb/Gost-ip6/raw/v0.6/Gost.sh)

درود سروش عزیز حتما بررسی میکنم

**Comment by pjalil74** [comment]
سلام استاد مولتی پورت اوکی شده یا نه ؟

**Comment by masoudgb** [comment]
> سلام استاد مولتی پورت اوکی شده یا نه ؟

سلام دوست عزیزم
نباید مشکلی باشه
