### ISSUE TITLE
مشکل پورت

### ISSUE THREAD

**Issue by Mahdi84S** [masoudgb/Gost-ip6#26]
درود
در تانل ipv6 رنج پورت بعضی از پورت ها کار نمیکنه مثلا پورت 38672 و پورت های نزدیک به این عدد کار نمیکنه
ممنون میشم پیگیری کنید

**Comment by nika1367** [comment]
بخاطر اینکه رنج پورت ها رو کامل باز نکردن

**Comment by masoudgb** [comment]
> درود در تانل ipv6 رنج پورت بعضی از پورت ها کار نمیکنه مثلا پورت 38672 و پورت های نزدیک به این عدد کار نمیکنه ممنون میشم پیگیری کنید

لطفاً
بصورت دستی گوست رو استارت بفرمایید اگر مشکل رفع شد لطفاً اطلاع بدید
systemctl start gost_0 
systemctl start gost_1
systemctl start gost_2
systemctl start gost_3
systemctl start gost_4

**Comment by Mahdi84S** [comment]
اون پورت درست شد ولی بازم پورت های دیگه ای هم هست مشکل داره

**Comment by masoudgb** [comment]
دستورات زیر رو امتحان کنید خروجی فایلی که استارت نشد رو ارسال بفرمایید

systemctl status gost_0
systemctl status gost_1
systemctl status gost_2
systemctl status gost_3
systemctl status gost_4

**Comment by sorushamox2357** [comment]
سلام و عرض ادب و خسته نباشید ممنون بابت این اسکریپتی که زحمت کشیدید تهیه کردید واقعا کار رو راحت میکنه و واقعا هم سریع هست کانکشن ها هم واقعا استیبل کار میکنن و سرعت خوبی داره

فقط موقع تعریف کردن پورت موقع تعریف رنج 54,65000  تقریبا شانسی یکبار برای من کارکرد ولی اکثر مواقع این حالت کار نمیکنه اگر این مورد هم اصلاح بشه دیگه نور علی نور هست 

من میام بعضی وقت ها از 5 هزار تا 20 هزار یکبار اجرا میکنم دفعه بعدی از 5 هزار تا 30 هزار 
بعد تا 50 هزار بعد تا 65 هزار اجرا میکنم و کار میکنه این طوری بجز رنج پورت 30 هزار تا 40 هزار باقی پورت ها فعال میشن و به کار میوفتن

**Comment by masoudgb** [comment]
سلام عزیزم سپاسگزارم از ابراز محبتت 🌹
پورت 38672 رو از فایل گوست سرویس بصورت دستی حذف بفرمایید و گوست رو استارت کنید نتیجه رو اطلاع بدید لطفا

**Comment by nika1367** [comment]
> سلام عزیزم سپاسگزارم از ابراز محبتت 🌹 پورت 38672 رو از فایل گوست سرویس بصورت دستی حذف بفرمایید و گوست رو استارت کنید نتیجه رو اطلاع بدید لطفا

استاد همچنان بگیر نگیر پورتاهارو ازاد میکنه چرا تا 65535 باز نکردید؟ بعد هم به قول دوستمون وقتی از 10 هزار تا 20 میزاری میاره و ..... لطفا اگر پورتهارو از 23 تا 65535 باز کنید و پورت های مورد استفاده گوست هم skip بشه و این قضیه حل بشه عالی میشه

**Comment by masoudgb** [comment]
> > سلام عزیزم سپاسگزارم از ابراز محبتت 🌹 پورت 38672 رو از فایل گوست سرویس بصورت دستی حذف بفرمایید و گوست رو استارت کنید نتیجه رو اطلاع بدید لطفا
> 
> استاد همچنان بگیر نگیر پورتاهارو ازاد میکنه چرا تا 65535 باز نکردید؟ بعد هم به قول دوستمون وقتی از 10 هزار تا 20 میزاری میاره و ..... لطفا اگر پورتهارو از 23 تا 65535 باز کنید و پورت های مورد استفاده گوست هم skip بشه و این قضیه حل بشه عالی میشه

مشکلاتی با باز کردن کامل رنج پورت پیش میاد که هنوز رفع نشده، بطور پیش فرض گوست از پورتهای ورودی محدود پشتیبانی می‌کنه
تلاش میکنم در آپدیت های بعدی بتونم این محدودیت رو رفع کنم
