### ISSUE TITLE
multi port

### ISSUE THREAD

**Issue by nika1367** [masoudgb/Gost-ip6#27]
با سلام قرار بود پورت ها از 23 الی 65523 باز بشه ولی در برنامه گفته 53 تا 65000 ولی در عمل از 38823 باز میکنه لغایت 65000

**Comment by masoudgb** [comment]
درود وقت بخیر پورتها از 54 تا 65000 میتونن باز باشن
لطفاً گوست را بصورت دستی استارت بفرمایید و اطلاع بدید
systemctl start gost_0
systemctl start gost_1
systemctl start gost_2
systemctl start gost_3
systemctl start gost_4

**Comment by nika1367** [comment]
برای بنده فقط این میاد systemctl start gost_0 بعد هم تمام میشه .. موفقیت میده پنل بالا اوردم با ورژن 1.2

ولی استاد پورت ها کامل باز نیستا بازم چک میکنم .. چرا از 23 نگرفتید تا 65523 ؟

**Comment by nika1367** [comment]
> درود وقت بخیر پورتها از 54 تا 65000 میتونن باز باشن لطفاً گوست را بصورت دستی استارت بفرمایید و اطلاع بدید systemctl start gost_0 systemctl start gost_1 systemctl start gost_2 systemctl start gost_3 systemctl start gost_4

برای بنده فقط این میاد systemctl start gost_0 بعد هم تمام میشه .. موفقیت میده پنل بالا اوردم با ورژن 1.2

ولی استاد پورت ها کامل باز نیستا بازم چک میکنم .. چرا از 23 نگرفتید تا 65523 ؟

**Comment by masoudgb** [comment]
> > درود وقت بخیر پورتها از 54 تا 65000 میتونن باز باشن لطفاً گوست را بصورت دستی استارت بفرمایید و اطلاع بدید systemctl start gost_0 systemctl start gost_1 systemctl start gost_2 systemctl start gost_3 systemctl start gost_4
> 
> برای بنده فقط این میاد systemctl start gost_0 بعد هم تمام میشه .. موفقیت میده پنل بالا اوردم با ورژن 1.2
> 
> ولی استاد پورت ها کامل باز نیستا بازم چک میکنم .. چرا از 23 نگرفتید تا 65523 ؟

نیکا جان پورت 53 توسط گوست استفاده میشه باقی رو میتونید بصورت دستی اضافه کنید
لطفاً یکبار لغو نصب کنید و مجدد امتحان کنید از پورت 54 تا 65000 رو وارد کنید
