### ISSUE TITLE
استفاده از پورت ۵۲ ؟

### ISSUE THREAD

**Issue by omidmehdizadeh2** [masoudgb/Gost-ip6#28]
با عرض سلام خدمت شما دوست عزیز
من متاسفانه سرورم روی پورت ۵۲ هست . 
اگر از این پورت استفاده کنم مشکلی به وجود میاد ؟
و اگر راهی داره بفرمایید .

دو تا نسخه هست : ورژن ۲.۷ و ورژن ۳ چه فرقی دارند ؟

و سوال آخر اینکه حتما از BBR باید استفاده کنم ؟

**Comment by masoudgb** [comment]
درود امید جان
مشکلی نیست از طریق گزینه اضافه کردن ایپی جدید انجام بدید 
نسخه 2 رسمی است و 3 آخرین نگارش
استفاده از bbr انتخابی است در برخی سرور ها موثری است

**Comment by omidmehdizadeh2** [comment]
سپاسگزارم مسعود عزیز
و ممنون از شما بابت پاسخگویی سریع .

**Comment by masoudgb** [comment]
> سپاسگزارم مسعود عزیز و ممنون از شما بابت پاسخگویی سریع .

خواهش میکنم امید جان 🌹
