### ISSUE TITLE
ریستارت اتوماتیک 

### ISSUE THREAD

**Issue by milad97** [masoudgb/Gost-ip6#29]
سلام وقت بخیر 

بعد از چند ساعت که tunel انجام میشه سرعت افت میکنه ریستارت که میکنم اوکی میشه .امکانش هست گزینه ریستارت اتوماتیک رو به اسکریپت اضافه کنید

**Comment by masoudgb** [comment]
درود وقت بخیر 
در آپدیت بعدی لحاظ میشه
البته مشکلی به این شکل که فرمودید گزارش نشده 
از میزان رم و سی پی یو مناسب با مصرف سرور هم اطمینان حاصل بفرمایید
