### ISSUE TITLE
تعداد کانکشن

### ISSUE THREAD

**Issue by FRIBANGI** [masoudgb/Gost-ip6#3]
سلام وقت بخیر میخواستم بدونم روی تعداد کانکشن بالا هم آیا کار میکنه ؟ 
و سرعت به همون صورت باقی میمونه یا خیر

**Comment by masoudgb** [comment]
درود وقت بخیر 🌹
تا 200 کانکشن آنلاین بررسی شده هیچ مشکلی گزارش نشده، اگر اشکالی بوجود اومد لطفا بفرمایید.
