### ISSUE TITLE
مشکل در نصب

### ISSUE THREAD

**Issue by mr-mr7** [masoudgb/Gost-ip6#32]
سلام
من اسکریپت رو نصب کردم
وقتی انتخاب میکنم ک روی کدوم شبکه باشه مثلا TCP بعد این مرحله گیر میکنه و جلو نمیره
کلا هم 3 تا پورت تستی رو میخواستم اضافه کنم
Waiting for cache lock: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 2634 (apt-get)... 69s

**Comment by mr-mr7** [comment]
مشکل حل شد
راه حل: 
https://askubuntu.com/questions/1109982/e-could-not-get-lock-var-lib-dpkg-lock-frontend-open-11-resource-temporari

**Comment by masoudgb** [comment]
> مشکل حل شد راه حل: https://askubuntu.com/questions/1109982/e-could-not-get-lock-var-lib-dpkg-lock-frontend-open-11-resource-temporari

خوشحالم که راه حل رو پیدا کردید
ممنون از اینکه راه کار رو به اشتراک گذاشتید 🌹
