### ISSUE TITLE
عدم اتصال

### ISSUE THREAD

**Issue by NIKA5050** [masoudgb/Gost-ip6#35]
سلام به چندین روش تانل سیکس و فور میزنم که اولا یا بالا نمیاره و اگرم بالا بیاره پنلو داخلش هرچی یوزر بسازی وصل نمیشه qr code کپی میکنم ارور tls میده not connect میزنه و وقتی هم ریبوت میکنه سرور داخل یجوری قفلی میشه حتی با منابع خیلی بالا و دیگه کلا پنلم بعد ریبوت بالا نمیاره دوتا پورت انتخاب کردم دیگه مغزم سوت کشیده دوست عزیز چیکار کنم ؟؟

**Comment by masoudgb** [comment]
> سلام به چندین روش تانل سیکس و فور میزنم که اولا یا بالا نمیاره و اگرم بالا بیاره پنلو داخلش هرچی یوزر بسازی وصل نمیشه qr code کپی میکنم ارور tls میده not connect میزنه و وقتی هم ریبوت میکنه سرور داخل یجوری قفلی میشه حتی با منابع خیلی بالا و دیگه کلا پنلم بعد ریبوت بالا نمیاره دوتا پورت انتخاب کردم دیگه مغزم سوت کشیده دوست عزیز چیکار کنم ؟؟

درود وقت بخیر 
مشکلاتی که فرمودید مربوط به سرویس گوست نیست
در مورد سیستم عامل مورد استفاده ، اسکریپت های احتمالی که روی پنل ایران دارید و خطاهای داخل ترمینال توضیح بدید لطفاً

**Comment by NIKA5050** [comment]
> > سلام به چندین روش تانل سیکس و فور میزنم که اولا یا بالا نمیاره و اگرم بالا بیاره پنلو داخلش هرچی یوزر بسازی وصل نمیشه qr code کپی میکنم ارور tls میده not connect میزنه و وقتی هم ریبوت میکنه سرور داخل یجوری قفلی میشه حتی با منابع خیلی بالا و دیگه کلا پنلم بعد ریبوت بالا نمیاره دوتا پورت انتخاب کردم دیگه مغزم سوت کشیده دوست عزیز چیکار کنم ؟؟
> 
> درود وقت بخیر مشکلاتی که فرمودید مربوط به سرویس گوست نیست در مورد سیستم عامل مورد استفاده ، اسکریپت های احتمالی که روی پنل ایران دارید و خطاهای داخل ترمینال توضیح بدید لطفاً

سیستم عامل اوبونتو 20 و اسکریپت خاصی ندارم جز تانل ipsix و بعد نصب چه ورژن 2 و چه 3 سرور فریز میشه اگرم پنل بالا بیاد فقط 1 دقیقه کار میکنه و مجدد فریز میشه ! روی منابع خیلی بالا دارم ران میکنم و دنبال فایل لاگ میگردم ببینم داستان چیه فریز میکنه ..
یه سوال چرا اسکریپ ران میکنم میزنه 1.2 در واقع شما اپدیت 1.5 دادید که ؟

**Comment by masoudgb** [comment]
> > > سلام به چندین روش تانل سیکس و فور میزنم که اولا یا بالا نمیاره و اگرم بالا بیاره پنلو داخلش هرچی یوزر بسازی وصل نمیشه qr code کپی میکنم ارور tls میده not connect میزنه و وقتی هم ریبوت میکنه سرور داخل یجوری قفلی میشه حتی با منابع خیلی بالا و دیگه کلا پنلم بعد ریبوت بالا نمیاره دوتا پورت انتخاب کردم دیگه مغزم سوت کشیده دوست عزیز چیکار کنم ؟؟
> > 
> > 
> > درود وقت بخیر مشکلاتی که فرمودید مربوط به سرویس گوست نیست در مورد سیستم عامل مورد استفاده ، اسکریپت های احتمالی که روی پنل ایران دارید و خطاهای داخل ترمینال توضیح بدید لطفاً
> 
> سیستم عامل اوبونتو 20 و اسکریپت خاصی ندارم جز تانل ipsix و بعد نصب چه ورژن 2 و چه 3 سرور فریز میشه اگرم پنل بالا بیاد فقط 1 دقیقه کار میکنه و مجدد فریز میشه ! روی منابع خیلی بالا دارم ران میکنم و دنبال فایل لاگ میگردم ببینم داستان چیه فریز میکنه .. یه سوال چرا اسکریپ ران میکنم میزنه 1.2 در واقع شما اپدیت 1.5 دادید که ؟

لطفاً سیستم عامل رو مجدد نصب کنید و فقط اسکریپت رو نصب بفرمایید و نتیجه رو اطلاع بدید
شما وقتی از گوست استفاده میکنید نیاز به تانل دیگری ندارید
اگر میخواهید از گزینه ایپی 6 استفاده بفرمایید از جایی ایران را تهیه کنید که به شما ایپی 6 ارایه دهد

**Comment by NIKA5050** [comment]
> > > > سلام به چندین روش تانل سیکس و فور میزنم که اولا یا بالا نمیاره و اگرم بالا بیاره پنلو داخلش هرچی یوزر بسازی وصل نمیشه qr code کپی میکنم ارور tls میده not connect میزنه و وقتی هم ریبوت میکنه سرور داخل یجوری قفلی میشه حتی با منابع خیلی بالا و دیگه کلا پنلم بعد ریبوت بالا نمیاره دوتا پورت انتخاب کردم دیگه مغزم سوت کشیده دوست عزیز چیکار کنم ؟؟
> > > 
> > > 
> > > درود وقت بخیر مشکلاتی که فرمودید مربوط به سرویس گوست نیست در مورد سیستم عامل مورد استفاده ، اسکریپت های احتمالی که روی پنل ایران دارید و خطاهای داخل ترمینال توضیح بدید لطفاً
> > 
> > 
> > سیستم عامل اوبونتو 20 و اسکریپت خاصی ندارم جز تانل ipsix و بعد نصب چه ورژن 2 و چه 3 سرور فریز میشه اگرم پنل بالا بیاد فقط 1 دقیقه کار میکنه و مجدد فریز میشه ! روی منابع خیلی بالا دارم ران میکنم و دنبال فایل لاگ میگردم ببینم داستان چیه فریز میکنه .. یه سوال چرا اسکریپ ران میکنم میزنه 1.2 در واقع شما اپدیت 1.5 دادید که ؟
> 
> لطفاً سیستم عامل رو مجدد نصب کنید و فقط اسکریپت رو نصب بفرمایید و نتیجه رو اطلاع بدید شما وقتی از گوست استفاده میکنید نیاز به تانل دیگری ندارید اگر میخواهید از گزینه ایپی 6 استفاده بفرمایید از جایی ایران را تهیه کنید که به شما ایپی 6 ارایه دهد

مجدد نصب کردم روی اوبونتو 22 با ایپی لوکال جواب داد یکبار حالت مولتی پورت زدم مثلا یوزر پورت 47489 و 52330 که فقط یکبار جواب داد دیگر جواب نداد و ارور fail to detect internet connection: net http: tls handshake tiomeout داد و مجدد اسکریپ پاک کردم و فقط پورت دستی انتخابی زدم پورت پنل 5050 و یوزر اکانت 443 فقط همین دوتا ..

با یوزر اکانت 443 تست کردم روی adsl جواب میده ولی روی ایرانسل جالبه جواب نمیده ارور fail to detect internet connection: net http: tls handshake tiomeout میزنه روی همراه اولم اوکیه ولی ایرانسل جواب نمیده ..
حالت مولتی پورتم که کلا جواب نمیده روی هیچ خطی ارور بالا میزنه .. ولی روی اوبونتو 22 فریز نشد

**Comment by masoudgb** [comment]
> > > > > سلام به چندین روش تانل سیکس و فور میزنم که اولا یا بالا نمیاره و اگرم بالا بیاره پنلو داخلش هرچی یوزر بسازی وصل نمیشه qr code کپی میکنم ارور tls میده not connect میزنه و وقتی هم ریبوت میکنه سرور داخل یجوری قفلی میشه حتی با منابع خیلی بالا و دیگه کلا پنلم بعد ریبوت بالا نمیاره دوتا پورت انتخاب کردم دیگه مغزم سوت کشیده دوست عزیز چیکار کنم ؟؟
> > > > 
> > > > 
> > > > درود وقت بخیر مشکلاتی که فرمودید مربوط به سرویس گوست نیست در مورد سیستم عامل مورد استفاده ، اسکریپت های احتمالی که روی پنل ایران دارید و خطاهای داخل ترمینال توضیح بدید لطفاً
> > > 
> > > 
> > > سیستم عامل اوبونتو 20 و اسکریپت خاصی ندارم جز تانل ipsix و بعد نصب چه ورژن 2 و چه 3 سرور فریز میشه اگرم پنل بالا بیاد فقط 1 دقیقه کار میکنه و مجدد فریز میشه ! روی منابع خیلی بالا دارم ران میکنم و دنبال فایل لاگ میگردم ببینم داستان چیه فریز میکنه .. یه سوال چرا اسکریپ ران میکنم میزنه 1.2 در واقع شما اپدیت 1.5 دادید که ؟
> > 
> > 
> > لطفاً سیستم عامل رو مجدد نصب کنید و فقط اسکریپت رو نصب بفرمایید و نتیجه رو اطلاع بدید شما وقتی از گوست استفاده میکنید نیاز به تانل دیگری ندارید اگر میخواهید از گزینه ایپی 6 استفاده بفرمایید از جایی ایران را تهیه کنید که به شما ایپی 6 ارایه دهد
> 
> مجدد نصب کردم روی اوبونتو 22 با ایپی لوکال جواب داد یکبار حالت مولتی پورت زدم مثلا یوزر پورت 47489 و 52330 که فقط یکبار جواب داد دیگر جواب نداد و ارور fail to detect internet connection: net http: tls handshake tiomeout داد و مجدد اسکریپ پاک کردم و فقط پورت دستی انتخابی زدم پورت پنل 5050 و یوزر اکانت 443 فقط همین دوتا ..
> 
> با یوزر اکانت 443 تست کردم روی adsl جواب میده ولی روی ایرانسل جالبه جواب نمیده ارور fail to detect internet connection: net http: tls handshake tiomeout میزنه روی همراه اولم اوکیه ولی ایرانسل جواب نمیده .. حالت مولتی پورتم که کلا جواب نمیده روی هیچ خطی ارور بالا میزنه .. ولی روی اوبونتو 22 فریز نشد

مشکل مربوط به سرور ایران میشه از کجا تهیه کردید

**Comment by NIKA5050** [comment]
> > > > > > سلام به چندین روش تانل سیکس و فور میزنم که اولا یا بالا نمیاره و اگرم بالا بیاره پنلو داخلش هرچی یوزر بسازی وصل نمیشه qr code کپی میکنم ارور tls میده not connect میزنه و وقتی هم ریبوت میکنه سرور داخل یجوری قفلی میشه حتی با منابع خیلی بالا و دیگه کلا پنلم بعد ریبوت بالا نمیاره دوتا پورت انتخاب کردم دیگه مغزم سوت کشیده دوست عزیز چیکار کنم ؟؟
> > > > > 
> > > > > 
> > > > > درود وقت بخیر مشکلاتی که فرمودید مربوط به سرویس گوست نیست در مورد سیستم عامل مورد استفاده ، اسکریپت های احتمالی که روی پنل ایران دارید و خطاهای داخل ترمینال توضیح بدید لطفاً
> > > > 
> > > > 
> > > > سیستم عامل اوبونتو 20 و اسکریپت خاصی ندارم جز تانل ipsix و بعد نصب چه ورژن 2 و چه 3 سرور فریز میشه اگرم پنل بالا بیاد فقط 1 دقیقه کار میکنه و مجدد فریز میشه ! روی منابع خیلی بالا دارم ران میکنم و دنبال فایل لاگ میگردم ببینم داستان چیه فریز میکنه .. یه سوال چرا اسکریپ ران میکنم میزنه 1.2 در واقع شما اپدیت 1.5 دادید که ؟
> > > 
> > > 
> > > لطفاً سیستم عامل رو مجدد نصب کنید و فقط اسکریپت رو نصب بفرمایید و نتیجه رو اطلاع بدید شما وقتی از گوست استفاده میکنید نیاز به تانل دیگری ندارید اگر میخواهید از گزینه ایپی 6 استفاده بفرمایید از جایی ایران را تهیه کنید که به شما ایپی 6 ارایه دهد
> > 
> > 
> > مجدد نصب کردم روی اوبونتو 22 با ایپی لوکال جواب داد یکبار حالت مولتی پورت زدم مثلا یوزر پورت 47489 و 52330 که فقط یکبار جواب داد دیگر جواب نداد و ارور fail to detect internet connection: net http: tls handshake tiomeout داد و مجدد اسکریپ پاک کردم و فقط پورت دستی انتخابی زدم پورت پنل 5050 و یوزر اکانت 443 فقط همین دوتا ..
> > با یوزر اکانت 443 تست کردم روی adsl جواب میده ولی روی ایرانسل جالبه جواب نمیده ارور fail to detect internet connection: net http: tls handshake tiomeout میزنه روی همراه اولم اوکیه ولی ایرانسل جواب نمیده .. حالت مولتی پورتم که کلا جواب نمیده روی هیچ خطی ارور بالا میزنه .. ولی روی اوبونتو 22 فریز نشد
> 
> مشکل مربوط به سرور ایران میشه از کجا تهیه کردید

h

**Comment by NIKA5050** [comment]
> > > > > > سلام به چندین روش تانل سیکس و فور میزنم که اولا یا بالا نمیاره و اگرم بالا بیاره پنلو داخلش هرچی یوزر بسازی وصل نمیشه qr code کپی میکنم ارور tls میده not connect میزنه و وقتی هم ریبوت میکنه سرور داخل یجوری قفلی میشه حتی با منابع خیلی بالا و دیگه کلا پنلم بعد ریبوت بالا نمیاره دوتا پورت انتخاب کردم دیگه مغزم سوت کشیده دوست عزیز چیکار کنم ؟؟
> > > > > 
> > > > > 
> > > > > درود وقت بخیر مشکلاتی که فرمودید مربوط به سرویس گوست نیست در مورد سیستم عامل مورد استفاده ، اسکریپت های احتمالی که روی پنل ایران دارید و خطاهای داخل ترمینال توضیح بدید لطفاً
> > > > 
> > > > 
> > > > سیستم عامل اوبونتو 20 و اسکریپت خاصی ندارم جز تانل ipsix و بعد نصب چه ورژن 2 و چه 3 سرور فریز میشه اگرم پنل بالا بیاد فقط 1 دقیقه کار میکنه و مجدد فریز میشه ! روی منابع خیلی بالا دارم ران میکنم و دنبال فایل لاگ میگردم ببینم داستان چیه فریز میکنه .. یه سوال چرا اسکریپ ران میکنم میزنه 1.2 در واقع شما اپدیت 1.5 دادید که ؟
> > > 
> > > 
> > > لطفاً سیستم عامل رو مجدد نصب کنید و فقط اسکریپت رو نصب بفرمایید و نتیجه رو اطلاع بدید شما وقتی از گوست استفاده میکنید نیاز به تانل دیگری ندارید اگر میخواهید از گزینه ایپی 6 استفاده بفرمایید از جایی ایران را تهیه کنید که به شما ایپی 6 ارایه دهد
> > 
> > 
> > مجدد نصب کردم روی اوبونتو 22 با ایپی لوکال جواب داد یکبار حالت مولتی پورت زدم مثلا یوزر پورت 47489 و 52330 که فقط یکبار جواب داد دیگر جواب نداد و ارور fail to detect internet connection: net http: tls handshake tiomeout داد و مجدد اسکریپ پاک کردم و فقط پورت دستی انتخابی زدم پورت پنل 5050 و یوزر اکانت 443 فقط همین دوتا ..
> > با یوزر اکانت 443 تست کردم روی adsl جواب میده ولی روی ایرانسل جالبه جواب نمیده ارور fail to detect internet connection: net http: tls handshake tiomeout میزنه روی همراه اولم اوکیه ولی ایرانسل جواب نمیده .. حالت مولتی پورتم که کلا جواب نمیده روی هیچ خطی ارور بالا میزنه .. ولی روی اوبونتو 22 فریز نشد
> 
> مشکل مربوط به سرور ایران میشه از کجا تهیه کردید
از اسیا یعنی مشکل از سرورهای ایرانه ؟ راه حل خاضی داره یا همین جور تست کنم از جاهای دیگر .. بعد استاد چرا ورژن 1.2 میاره 1.5 نمیاره بالا ؟

**Comment by NIKA5050** [comment]
> > > > > > سلام به چندین روش تانل سیکس و فور میزنم که اولا یا بالا نمیاره و اگرم بالا بیاره پنلو داخلش هرچی یوزر بسازی وصل نمیشه qr code کپی میکنم ارور tls میده not connect میزنه و وقتی هم ریبوت میکنه سرور داخل یجوری قفلی میشه حتی با منابع خیلی بالا و دیگه کلا پنلم بعد ریبوت بالا نمیاره دوتا پورت انتخاب کردم دیگه مغزم سوت کشیده دوست عزیز چیکار کنم ؟؟
> > > > > 
> > > > > 
> > > > > درود وقت بخیر مشکلاتی که فرمودید مربوط به سرویس گوست نیست در مورد سیستم عامل مورد استفاده ، اسکریپت های احتمالی که روی پنل ایران دارید و خطاهای داخل ترمینال توضیح بدید لطفاً
> > > > 
> > > > 
> > > > سیستم عامل اوبونتو 20 و اسکریپت خاصی ندارم جز تانل ipsix و بعد نصب چه ورژن 2 و چه 3 سرور فریز میشه اگرم پنل بالا بیاد فقط 1 دقیقه کار میکنه و مجدد فریز میشه ! روی منابع خیلی بالا دارم ران میکنم و دنبال فایل لاگ میگردم ببینم داستان چیه فریز میکنه .. یه سوال چرا اسکریپ ران میکنم میزنه 1.2 در واقع شما اپدیت 1.5 دادید که ؟
> > > 
> > > 
> > > لطفاً سیستم عامل رو مجدد نصب کنید و فقط اسکریپت رو نصب بفرمایید و نتیجه رو اطلاع بدید شما وقتی از گوست استفاده میکنید نیاز به تانل دیگری ندارید اگر میخواهید از گزینه ایپی 6 استفاده بفرمایید از جایی ایران را تهیه کنید که به شما ایپی 6 ارایه دهد
> > 
> > 
> > مجدد نصب کردم روی اوبونتو 22 با ایپی لوکال جواب داد یکبار حالت مولتی پورت زدم مثلا یوزر پورت 47489 و 52330 که فقط یکبار جواب داد دیگر جواب نداد و ارور fail to detect internet connection: net http: tls handshake tiomeout داد و مجدد اسکریپ پاک کردم و فقط پورت دستی انتخابی زدم پورت پنل 5050 و یوزر اکانت 443 فقط همین دوتا ..
> > با یوزر اکانت 443 تست کردم روی adsl جواب میده ولی روی ایرانسل جالبه جواب نمیده ارور fail to detect internet connection: net http: tls handshake tiomeout میزنه روی همراه اولم اوکیه ولی ایرانسل جواب نمیده .. حالت مولتی پورتم که کلا جواب نمیده روی هیچ خطی ارور بالا میزنه .. ولی روی اوبونتو 22 فریز نشد
> 
> مشکل مربوط به سرور ایران میشه از کجا تهیه کردید

از اسیا یعنی مشکل از سرورهای ایرانه ؟ راه حل خاضی داره یا همین جور تست کنم از جاهای دیگر .. بعد استاد چرا ورژن 1.2 میاره 1.5 نمیاره بالا ؟

**Comment by NIKA5050** [comment]
> > > > > > سلام به چندین روش تانل سیکس و فور میزنم که اولا یا بالا نمیاره و اگرم بالا بیاره پنلو داخلش هرچی یوزر بسازی وصل نمیشه qr code کپی میکنم ارور tls میده not connect میزنه و وقتی هم ریبوت میکنه سرور داخل یجوری قفلی میشه حتی با منابع خیلی بالا و دیگه کلا پنلم بعد ریبوت بالا نمیاره دوتا پورت انتخاب کردم دیگه مغزم سوت کشیده دوست عزیز چیکار کنم ؟؟
> > > > > 
> > > > > 
> > > > > درود وقت بخیر مشکلاتی که فرمودید مربوط به سرویس گوست نیست در مورد سیستم عامل مورد استفاده ، اسکریپت های احتمالی که روی پنل ایران دارید و خطاهای داخل ترمینال توضیح بدید لطفاً
> > > > 
> > > > 
> > > > سیستم عامل اوبونتو 20 و اسکریپت خاصی ندارم جز تانل ipsix و بعد نصب چه ورژن 2 و چه 3 سرور فریز میشه اگرم پنل بالا بیاد فقط 1 دقیقه کار میکنه و مجدد فریز میشه ! روی منابع خیلی بالا دارم ران میکنم و دنبال فایل لاگ میگردم ببینم داستان چیه فریز میکنه .. یه سوال چرا اسکریپ ران میکنم میزنه 1.2 در واقع شما اپدیت 1.5 دادید که ؟
> > > 
> > > 
> > > لطفاً سیستم عامل رو مجدد نصب کنید و فقط اسکریپت رو نصب بفرمایید و نتیجه رو اطلاع بدید شما وقتی از گوست استفاده میکنید نیاز به تانل دیگری ندارید اگر میخواهید از گزینه ایپی 6 استفاده بفرمایید از جایی ایران را تهیه کنید که به شما ایپی 6 ارایه دهد
> > 
> > 
> > مجدد نصب کردم روی اوبونتو 22 با ایپی لوکال جواب داد یکبار حالت مولتی پورت زدم مثلا یوزر پورت 47489 و 52330 که فقط یکبار جواب داد دیگر جواب نداد و ارور fail to detect internet connection: net http: tls handshake tiomeout داد و مجدد اسکریپ پاک کردم و فقط پورت دستی انتخابی زدم پورت پنل 5050 و یوزر اکانت 443 فقط همین دوتا ..
> > با یوزر اکانت 443 تست کردم روی adsl جواب میده ولی روی ایرانسل جالبه جواب نمیده ارور fail to detect internet connection: net http: tls handshake tiomeout میزنه روی همراه اولم اوکیه ولی ایرانسل جواب نمیده .. حالت مولتی پورتم که کلا جواب نمیده روی هیچ خطی ارور بالا میزنه .. ولی روی اوبونتو 22 فریز نشد
> 
> مشکل مربوط به سرور ایران میشه از کجا تهیه کردید

از اسیا یعنی مشکل از سرورهای ایرانه ؟ راه حل خاضی داره یا همین جور تست کنم از جاهای دیگر .. بعد استاد چرا ورژن 1.2 میاره 1.5 نمیاره بالا ؟

**Comment by NIKA5050** [comment]
> > > > > > سلام به چندین روش تانل سیکس و فور میزنم که اولا یا بالا نمیاره و اگرم بالا بیاره پنلو داخلش هرچی یوزر بسازی وصل نمیشه qr code کپی میکنم ارور tls میده not connect میزنه و وقتی هم ریبوت میکنه سرور داخل یجوری قفلی میشه حتی با منابع خیلی بالا و دیگه کلا پنلم بعد ریبوت بالا نمیاره دوتا پورت انتخاب کردم دیگه مغزم سوت کشیده دوست عزیز چیکار کنم ؟؟
> > > > > 
> > > > > 
> > > > > درود وقت بخیر مشکلاتی که فرمودید مربوط به سرویس گوست نیست در مورد سیستم عامل مورد استفاده ، اسکریپت های احتمالی که روی پنل ایران دارید و خطاهای داخل ترمینال توضیح بدید لطفاً
> > > > 
> > > > 
> > > > سیستم عامل اوبونتو 20 و اسکریپت خاصی ندارم جز تانل ipsix و بعد نصب چه ورژن 2 و چه 3 سرور فریز میشه اگرم پنل بالا بیاد فقط 1 دقیقه کار میکنه و مجدد فریز میشه ! روی منابع خیلی بالا دارم ران میکنم و دنبال فایل لاگ میگردم ببینم داستان چیه فریز میکنه .. یه سوال چرا اسکریپ ران میکنم میزنه 1.2 در واقع شما اپدیت 1.5 دادید که ؟
> > > 
> > > 
> > > لطفاً سیستم عامل رو مجدد نصب کنید و فقط اسکریپت رو نصب بفرمایید و نتیجه رو اطلاع بدید شما وقتی از گوست استفاده میکنید نیاز به تانل دیگری ندارید اگر میخواهید از گزینه ایپی 6 استفاده بفرمایید از جایی ایران را تهیه کنید که به شما ایپی 6 ارایه دهد
> > 
> > 
> > مجدد نصب کردم روی اوبونتو 22 با ایپی لوکال جواب داد یکبار حالت مولتی پورت زدم مثلا یوزر پورت 47489 و 52330 که فقط یکبار جواب داد دیگر جواب نداد و ارور fail to detect internet connection: net http: tls handshake tiomeout داد و مجدد اسکریپ پاک کردم و فقط پورت دستی انتخابی زدم پورت پنل 5050 و یوزر اکانت 443 فقط همین دوتا ..
> > با یوزر اکانت 443 تست کردم روی adsl جواب میده ولی روی ایرانسل جالبه جواب نمیده ارور fail to detect internet connection: net http: tls handshake tiomeout میزنه روی همراه اولم اوکیه ولی ایرانسل جواب نمیده .. حالت مولتی پورتم که کلا جواب نمیده روی هیچ خطی ارور بالا میزنه .. ولی روی اوبونتو 22 فریز نشد
> 
> مشکل مربوط به سرور ایران میشه از کجا تهیه کردید

بله چک کردم کلا این ایپی روی ایرانسل مسدود شده برای همین ارور tls میده حق با شماست .. ولی دوتا نکته همچنان روی حالت مولتی پورت میرم کلا پینگ نمیده و وقتی دستی انتخاب میکنم اوکیه.. واینکه روی اوبونتو 20 فریز میشه سرویس  من روی اوبونتو 22 ران کردم

**Comment by masoudgb** [comment]
یکبار دستور استارت گوست رو اجرا کنید ببینید آیا مشکل رفع میشه
systemctl start gost_0
systemctl start gost_1
systemctl start gost_2
systemctl start gost_3
systemctl start gost_4

**Comment by NIKA5050** [comment]
> systemctl start gost_4

استاد درست شد :) مرسی فقط چرا سرویس ران نمیشه یعنی موقع نصب میشه ولی تا الان یبار دیگه اجرا نکنیم نمیشه ؟

**Comment by NIKA5050** [comment]
> یکبار دستور استارت گوست رو اجرا کنید ببینید آیا مشکل رفع میشه systemctl start gost_0 systemctl start gost_1 systemctl start gost_2 systemctl start gost_3 systemctl start gost_4

استاد درست شد :) مرسی فقط چرا سرویس ران نمیشه یعنی موقع نصب میشه ولی تا الان یبار دیگه اجرا نکنیم نمیشه ؟

**Comment by masoudgb** [comment]
> > یکبار دستور استارت گوست رو اجرا کنید ببینید آیا مشکل رفع میشه systemctl start gost_0 systemctl start gost_1 systemctl start gost_2 systemctl start gost_3 systemctl start gost_4
> 
> استاد درست شد :) مرسی فقط چرا سرویس ران نمیشه یعنی موقع نصب میشه ولی تا الان یبار دیگه اجرا نکنیم نمیشه ؟

خواهش میکنم
مشکلی که فرمودید در آپدیت بعدی لحاظ میشه

**Comment by webadminlist** [comment]
درود بر شما
دستور ها رو زدم
ران نمیشه
اسکرین رو ببینید

![Screenshot 2024-02-17 232724](https://github.com/masoudgb/Gost-ip6/assets/148615831/8318bb8c-4275-4c54-b364-66cc770bda8b)


> یکبار دستور استارت گوست رو اجرا کنید ببینید آیا مشکل رفع میشه systemctl start gost_0 systemctl start gost_1 systemctl start gost_2 systemctl start gost_3 systemctl start gost_4

**Comment by masoudgb** [comment]
> درود بر شما دستور ها رو زدم ران نمیشه اسکرین رو ببینید
> 
> ![Screenshot 2024-02-17 232724](https://private-user-images.githubusercontent.com/148615831/305667631-8318bb8c-4275-4c54-b364-66cc770bda8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMDA4NDUsIm5iZiI6MTcwODIwMDU0NSwicGF0aCI6Ii8xNDg2MTU4MzEvMzA1NjY3NjMxLTgzMThiYjhjLTQyNzUtNGM1NC1iMzY0LTY2Y2M3NzBiZGE4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxN1QyMDA5MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOGViNjIxNjFmYWM1ZjQwMDQ1NzEwYjQxZTU3NmY1ODIxZDA2MjNkNTYwZTcyNzk4MThmZDVhOWMwYTBjNGFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aQs8DxnK37ma--etq4rQGUpzGCGMm1s9aZ681EsmUZk)
> 
> > یکبار دستور استارت گوست رو اجرا کنید ببینید آیا مشکل رفع میشه systemctl start gost_0 systemctl start gost_1 systemctl start gost_2 systemctl start gost_3 systemctl start gost_4

درود تنها یک فایل سرویس نوشته شده است
آیا از رنج پورت استفاده کردید

**Comment by webadminlist** [comment]
> > درود بر شما دستور ها رو زدم ران نمیشه اسکرین رو ببینید
> > ![Screenshot 2024-02-17 232724](https://private-user-images.githubusercontent.com/148615831/305667631-8318bb8c-4275-4c54-b364-66cc770bda8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMDA4NDUsIm5iZiI6MTcwODIwMDU0NSwicGF0aCI6Ii8xNDg2MTU4MzEvMzA1NjY3NjMxLTgzMThiYjhjLTQyNzUtNGM1NC1iMzY0LTY2Y2M3NzBiZGE4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxN1QyMDA5MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOGViNjIxNjFmYWM1ZjQwMDQ1NzEwYjQxZTU3NmY1ODIxZDA2MjNkNTYwZTcyNzk4MThmZDVhOWMwYTBjNGFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aQs8DxnK37ma--etq4rQGUpzGCGMm1s9aZ681EsmUZk)
> > > یکبار دستور استارت گوست رو اجرا کنید ببینید آیا مشکل رفع میشه systemctl start gost_0 systemctl start gost_1 systemctl start gost_2 systemctl start gost_3 systemctl start gost_4
> 
> درود تنها یک فایل سرویس نوشته شده است آیا از رنج پورت استفاده کردید


بله فقط یکیشون استارت میشه
خیر از رنج استفاده نمیکنم
چون کلا کار نمیکنه روی سرو های من رنج پورت

**Comment by masoudgb** [comment]
> > > درود بر شما دستور ها رو زدم ران نمیشه اسکرین رو ببینید
> > > ![Screenshot 2024-02-17 232724](https://private-user-images.githubusercontent.com/148615831/305667631-8318bb8c-4275-4c54-b364-66cc770bda8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMDA4NDUsIm5iZiI6MTcwODIwMDU0NSwicGF0aCI6Ii8xNDg2MTU4MzEvMzA1NjY3NjMxLTgzMThiYjhjLTQyNzUtNGM1NC1iMzY0LTY2Y2M3NzBiZGE4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxN1QyMDA5MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOGViNjIxNjFmYWM1ZjQwMDQ1NzEwYjQxZTU3NmY1ODIxZDA2MjNkNTYwZTcyNzk4MThmZDVhOWMwYTBjNGFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aQs8DxnK37ma--etq4rQGUpzGCGMm1s9aZ681EsmUZk)
> > > > یکبار دستور استارت گوست رو اجرا کنید ببینید آیا مشکل رفع میشه systemctl start gost_0 systemctl start gost_1 systemctl start gost_2 systemctl start gost_3 systemctl start gost_4
> > 
> > 
> > درود تنها یک فایل سرویس نوشته شده است آیا از رنج پورت استفاده کردید
> 
> بله فقط یکیشون استارت میشه خیر از رنج استفاده نمیکنم چون کلا کار نمیکنه روی سرو های من رنج پورت

وقتی پورت بصورت دستی وارد بشه بیش از 1 فایل ایجاد نمیشه 
مشکل چیه
