### ISSUE TITLE
ریست خودکار

### ISSUE THREAD

**Issue by omidmehdizadeh2** [masoudgb/Gost-ip6#38]
با عرض سلام مسعود عزیز
یه خسته نباشید باید بهتون بگم . واقعا خدا پدر و مادرت رو بیامرزه با این آموزش - امیدوارم همیشه موفق باشید .
چند تا سوال از شما دارم .
اول اینکه این تانل روی همه سرورهای ایرانی کار نمیکنه میشه چند تا سایت معرفی کنید که شما خودتون هم تست کرده باشید . مثلا آروان خیلی قطع و وصلی داره .
دوم اینکه 2 تا ورژن داره 2 و 3 (شما کدام رو پیشنهاد میکنید ؟ و چه فرقی دارند)
سوم اینکه شما یه آپشن اضافه کردید به عنوان ریست خودکار آیا حتما باید فعال کنیم ؟ ساعتی یا روزانه ؟ اگر نکنیم چی میشه ؟
واقعا اگر به این 3 تا سوال پاسخ بدید ممنونتون میشم .
شاید سوال خیلی از دوستان باشه .

**Comment by masoudgb** [comment]
> با عرض سلام مسعود عزیز یه خسته نباشید باید بهتون بگم . واقعا خدا پدر و مادرت رو بیامرزه با این آموزش - امیدوارم همیشه موفق باشید . چند تا سوال از شما دارم . اول اینکه این تانل روی همه سرورهای ایرانی کار نمیکنه میشه چند تا سایت معرفی کنید که شما خودتون هم تست کرده باشید . مثلا آروان خیلی قطع و وصلی داره . دوم اینکه 2 تا ورژن داره 2 و 3 (شما کدام رو پیشنهاد میکنید ؟ و چه فرقی دارند) سوم اینکه شما یه آپشن اضافه کردید به عنوان ریست خودکار آیا حتما باید فعال کنیم ؟ ساعتی یا روزانه ؟ اگر نکنیم چی میشه ؟ واقعا اگر به این 3 تا سوال پاسخ بدید ممنونتون میشم . شاید سوال خیلی از دوستان باشه .

سلام و ممنون امید عزیز از اظهار محبتت
روی افرانت، اسیاتک، اروان و ماهان کلود تست شده مشکلی نبوده البته توجه بفرمایید کیفیت سرورهای اروان متفاوت است باقی هم غالبأ همینطور هستن
گوست ورژن 2 اخرین نسخه رسمی از سازنده برنامه و گوست 3 آخرین نسخه از توسعه دهنده ای که پروژه گوست رو فورک کردند، در تستهای من گوست 3 در دراز مدت پایدار بود و پینگ‌ پایینتری داشت.
اجباری در استفاده از اتوماتیک ریاستارت وجود ندارد ولی پیشنهاد میکنم برای هر 8 ساعت تنظیم بفرمایید.

با احترام
