### ISSUE TITLE
gost relay or gost forwarder

### ISSUE THREAD

**Issue by arian2240** [masoudgb/Gost-ip6#39]
ایا گوست ۳ یا ۲ اسکریپت گوست ریلی هست یا گوست فورواردر؟

**Comment by masoudgb** [comment]
داده ها بصورت یک سویه توسط پروتکل tcp یا grcp به سمت مقصد هدایت می‌شوند.

**Comment by arian2240** [comment]
> داده ها بصورت یک سویه توسط پروتکل tcp یا grcp به سمت مقصد هدایت می‌شوند.

اوکی، پس ترافیک فوروارد میشه

**Comment by masoudgb** [comment]
> > داده ها بصورت یک سویه توسط پروتکل tcp یا grcp به سمت مقصد هدایت می‌شوند.
> 
> اوکی، پس ترافیک فوروارد میشه

بله
