### ISSUE TITLE
اجرا شدن

### ISSUE THREAD

**Issue by pooria1380** [masoudgb/Gost-ip6#4]
سلام
در زمان اجرا تونل این خطا رو میده
با چند سرور امتحان کردم
Failed to enable unit: File gost.service: No buffer space available
Failed to restart gost.service: Unit gost.service failed to load properly, please adjust/correct and reload service manager: No buffer space available
See system logs and 'systemctl status gost.service' for details.

**Comment by masoudgb** [comment]
ظاهراً مشکل در فضای ناکافی بافر برای اجرای گاست است
از دو دستور زیر کمک بگیرید تا خطاها را مشاهده کنید

systemctl status gost.service

journalctl -xe
