### ISSUE TITLE
تایمر ریست گوست

### ISSUE THREAD

**Issue by Mohammadaminsdr** [masoudgb/Gost-ip6#40]
سلام وقت بخیر ما تایم ریست رو تنظیم کردم رو 8 ساعت بعد اون تایم گوست ارور میده و مجبوریم دستی بریم گوست رو ریست بزنیم تا درست بشه چطور میتونیم درستش کنیم ؟

**Comment by masoudgb** [comment]
سلام محمد عزیز 
لطفاً خطای دریافتی رو ارسال بفرمایید 
یا اینکه ریاستارت رو غیر فعال کنید و مجدد فعال بفرمااید
