### ISSUE TITLE
لورفتن IP

### ISSUE THREAD

**Issue by NotMRGH** [masoudgb/Gost-ip6#41]
فکر کنم سیستم جدید فیلترینگ تشخیص میده جدیدن روی بعضی از دیتاسنتر های ایران که کلا تانل نمیخوره (بستگی به دیتاسنتر خارج هم داره)

و با 45 تا یوزر آیپیم فیلتر شد ( از حالت تمیز در امد)

**Comment by masoudgb** [comment]
> فکر کنم سیستم جدید فیلترینگ تشخیص میده جدیدن روی بعضی از دیتاسنتر های ایران که کلا تانل نمیخوره (بستگی به دیتاسنتر خارج هم داره)
> 
> و با 45 تا یوزر آیپیم فیلتر شد ( از حالت تمیز در امد)

درود وقت بخیر
با ایپی تمیز 4 مشکلی نیست، اگر میتونید از ایپی 6 استفاده کنید
