### ISSUE TITLE
مشکل در تغییر آی‌پی

### ISSUE THREAD

**Issue by AerEbi** [masoudgb/Gost-ip6#42]
اول ممنون بابت این اسکریپ خوبت.

وقتی می‌خوام آی‌پی رو عوض کنم - فرقی نداره IPv6 یا IPv4 باشه -  حتمن باید اول uninstall کنیم بعد مجدد از اول پیش بریم که گاهی بازم خوب جواب نمی‌ده. راهی هست بشه آی‌پی رو بدون اینکه از اول شروع کنیم عوض کرد؟ مثل حالتی که دستی توی ورژن2 عوض می‌کردیم؟

**Comment by masoudgb** [comment]
ممنون از ابراز محبتت دوست عزیزم 🌹
حتما بررسی میکنم اگر مشکلی ایجاد نشه در آپدیت بعدی لحاظ میشه
