### ISSUE TITLE
پر کردن هارد سرور از لاگ

### ISSUE THREAD

**Issue by alireza-mrx** [masoudgb/Gost-ip6#44]
سلام مسعود جان خسته نباشید
ممنون بخاطر زحمات و تلاشت
تانل گاست یک ایرادی داره که اگه لاگ رو غیرفعال نکنی هاردتو از لاگ پر میکنه
اگه ممکنه تو اسکریپتت این امکان رو اضافه کن که بدون ریستارت گاست بشه لاگ رو غیرفعال کرد

**Comment by masoudgb** [comment]
> سلام مسعود جان خسته نباشید ممنون بخاطر زحمات و تلاشت تانل گاست یک ایرادی داره که اگه لاگ رو غیرفعال نکنی هاردتو از لاگ پر میکنه اگه ممکنه تو اسکریپتت این امکان رو اضافه کن که بدون ریستارت گاست بشه لاگ رو غیرفعال کرد

سلام علیرضای عزیز ممنون از لطفت 
فایل لاگ در چه پچی نوشته شده

**Comment by alireza-mrx** [comment]
/var/log
syslog
![Captureaaa](https://github.com/masoudgb/Gost-ip6/assets/161974832/1b204baf-6a92-473a-8c9e-b85cca82199c)

**Comment by masoudgb** [comment]
> /var/log syslog ![Captureaaa](https://private-user-images.githubusercontent.com/161974832/309498297-1b204baf-6a92-473a-8c9e-b85cca82199c.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0MTIyNzYsIm5iZiI6MTcwOTQxMTk3NiwicGF0aCI6Ii8xNjE5NzQ4MzIvMzA5NDk4Mjk3LTFiMjA0YmFmLTZhOTItNDczYS04YzllLWI4NWNjYTgyMTk5Yy5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMlQyMDM5MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMmZlZWM0NTkwZTQyYTBlNGIzZmZhZDUzNWJmNjRkNGFjZGY0MDY4OTVhNzc1NmI5NzMyMmM3ZTFjZDExZGM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6E9_2q_20MkTOsOx4xKexx1Llveh5_8n95QmZI33-D4)

مربوط به گوست نیست علیرضا جان، لاگ رو بررسی کنید تا متوجه بشین مربوط به چیه

**Comment by alireza-mrx** [comment]
مسعود جان نتونستم عکس و سانسور کنم بعد دیدن بهم اطلاع بده پاکش کنم
![Captureaaa](https://github.com/masoudgb/Gost-ip6/assets/161974832/76313fc5-53a4-4b8d-97ba-e5dbd49b516f)

**Comment by masoudgb** [comment]
علیرضا جان دیدم پاک کن ممنون
از رنج پورت استفاده کردی.؟

**Comment by alireza-mrx** [comment]
نه عزیز برادر از پورت های تکی استفاده کردم
اینم بگم واقعا یوزرم زیاده و این مورد خیلی اذیت کننده میشه برام
مسعود جان واقعیت اینه من قبل اسکریپت شما هم از گوست استفاده میکردم و همین ایراد و داشتم داخل ریپازیتوری خود گوست خیلی دنبال راه حل گشتم انگار یه متغیر محلی باید قرار بدی که غیرفعالش کنه

**Comment by masoudgb** [comment]
> نه عزیز برادر از پورت های تکی استفاده کردم اینم بگم واقعا یوزرم زیاده و این مورد خیلی اذیت کننده میشه برام مسعود جان واقعیت اینه من قبل اسکریپت شما هم از گوست استفاده میکردم و همین ایراد و داشتم داخل ریپازیتوری خود گوست خیلی دنبال راه حل گشتم انگار یه متغیر محلی باید قرار بدی که غیرفعالش کنه

بررسی میکنم راهکار مناسبی پیدا بشه در آپدیت بعدی حتما لحاظ میکنم

**Comment by alireza-mrx** [comment]
مسعود جان این متغیر هستش
GOST_LOGGER_LEVEL=
مقادیرشو میشه تنظیم کرد
اینم لینک ایشو
https://github.com/go-gost/gost/issues/201

**Comment by masoudgb** [comment]
> مسعود جان این متغیر هستش GOST_LOGGER_LEVEL= مقادیرشو میشه تنظیم کرد اینم لینک ایشو [go-gost/gost#201](https://github.com/go-gost/gost/issues/201)

پیشنهاد بسیار خوبی هستش حتما در آپدیت بعدی لحاظ میشه

**Comment by masoudgb** [comment]
> > مسعود جان این متغیر هستش GOST_LOGGER_LEVEL= مقادیرشو میشه تنظیم کرد اینم لینک ایشو [go-gost/gost#201](https://github.com/go-gost/gost/issues/201)
> 
> پیشنهاد بسیار خوبی هستش حتما در آپدیت بعدی لحاظ میشه

علیرضا عزیز اسکریپت رو از مخزن مجدد نصب کن ببین با اضافه کردن مقدار برای لاگ‌های ایجاد شده گوست مشکل رفع شده یا خیر

**Comment by alireza-mrx** [comment]
مسعود جان چک کردم هنوز داره لاگ ثبت میکنه
راه حلی پیشنهاد میکنم احتمالا مشکل حل کنه
![IMG_20240303_012659](https://github.com/masoudgb/Gost-ip6/assets/161974832/02a7f879-1e0b-4ade-bb70-f6f30c21f347)

**Comment by masoudgb** [comment]
پیشنهاد خوبیه به فایل سرویس اضافه میکنم

**Comment by alireza-mrx** [comment]
خیلی آقایی
شرمنده آخر شبی اذیتت کردم بخاطر این قضیه جزئی

**Comment by masoudgb** [comment]
> خیلی آقایی شرمنده آخر شبی اذیتت کردم بخاطر این قضیه جزئی

خواهش میکنم عزیزم خوب شد گفتی 🙏❤️

**Comment by masoudgb** [comment]
> مسعود جان چک کردم هنوز داره لاگ ثبت میکنه راه حلی پیشنهاد میکنم احتمالا مشکل حل کنه ![IMG_20240303_012659](https://private-user-images.githubusercontent.com/161974832/309502916-02a7f879-1e0b-4ade-bb70-f6f30c21f347.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0MTg2NDUsIm5iZiI6MTcwOTQxODM0NSwicGF0aCI6Ii8xNjE5NzQ4MzIvMzA5NTAyOTE2LTAyYTdmODc5LTFlMGItNGFkZS1iYjcwLWY2ZjMwYzIxZjM0Ny5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMlQyMjI1NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NjY0ZGNlOGVhZWQ0NTQ4NGQzYTJmYjdlNmYwODY4N2ZhNjJlYWU3OGU0MThlZGY0ZTNiMzFhYzYzY2YxZThlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FuZkn50_GMpfxMVFzYShjHkrwfjda-BepQQ32mfjwf4)

تغییرات در فایل سرویس اعمال شد و الان دیگه تنها لاگ های ضروری نوشته میشه با توجه به استفاده از متغیر fatal اگر نصب مجدد انجام دادی لطفا اطلاع بده مشکل رفع شده یا خیر 🙏

**Comment by alireza-mrx** [comment]
فردا حتما رو سرور دیگه ای تست میکنم نتیجه رو اطلاع میدم،پاینده باشی❤️

**Comment by alireza-mrx** [comment]
عزیز برادر،تست کردم کامل حل شده بود 
خیلی ممنون وقت گذاشتی ❤️

**Comment by masoudgb** [comment]
خواهش میکنم عزیزم خوشحالم رفع اشکال شد.

> عزیز برادر،تست کردم کامل حل شده بود خیلی ممنون وقت گذاشتی ❤️
