### ISSUE TITLE
ارور failed fatal error

### ISSUE THREAD

**Issue by arian2240** [masoudgb/Gost-ip6#49]
gost_0.service - GO Simple Tunnel
     Loaded: loaded (/lib/systemd/system/gost_0.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sun 2024-03-10 16:24:05 CET; 26s ago
    Process: 6586 ExecStart=/usr/local/bin/gost -L=tcp://:95305/[2000:8888::1]:85305 -L=tcp://:85035/[2000.8888:1]:85035 -L=tcp://:6060/[2000.8888:1]:67>   Main PID: 6587 (code=exited, status=1/FAILURE)

Mar 10 16:24:05 S2-v1010 systemd[1]: Started GO Simple Tunnel.
Mar 10 16:24:05 S2-v1010 gost[6586]: {"level":"fatal","msg":"listen tcp: address 95305: invalid port","time":"2024-03-10T16:24:05.885+01:00"}
Mar 10 16:24:05 S2-v1010 systemd[1]: gost_0.service: Main process exited, code=exited, status=1/FAILURE
Mar 10 16:24:05 S2-v1010 systemd[1]: gost_0.service: Failed with result 'exit-code'.

**Comment by masoudgb** [comment]
> gost_0.service - GO Simple Tunnel Loaded: loaded (/lib/systemd/system/gost_0.service; enabled; vendor preset: enabled) Active: failed (Result: exit-code) since Sun 2024-03-10 16:24:05 CET; 26s ago Process: 6586 ExecStart=/usr/local/bin/gost -L=tcp://:95305/[2000:8888::1]:85305 -L=tcp://:85035/[2000.8888:1]:85035 -L=tcp://:6060/[2000.8888:1]:67> Main PID: 6587 (code=exited, status=1/FAILURE)
> 
> Mar 10 16:24:05 S2-v1010 systemd[1]: Started GO Simple Tunnel. Mar 10 16:24:05 S2-v1010 gost[6586]: {"level":"fatal","msg":"listen tcp: address 95305: invalid port","time":"2024-03-10T16:24:05.885+01:00"} Mar 10 16:24:05 S2-v1010 systemd[1]: gost_0.service: Main process exited, code=exited, status=1/FAILURE Mar 10 16:24:05 S2-v1010 systemd[1]: gost_0.service: Failed with result 'exit-code'.

پورتهارا اصلاح کنید
آخرین پورت 65535 است

**Comment by arian2240** [comment]
بله ممنون حواسم نبود یه سوال بهترین ریست تایم چقدره و هردفعه چقدر طول میکشه ریست بشه تونل

**Comment by masoudgb** [comment]
> بله ممنون حواسم نبود یه سوال بهترین ریست تایم چقدره و هردفعه چقدر طول میکشه ریست بشه تونل

پیشنهاد میکنم روی 8 ساعت قرار بدید ری استارت سرویس کمتر از یک ثانیه
