### ISSUE TITLE
عدم پینگ سرور داخل به خارج

### ISSUE THREAD

**Issue by NIKA5050** [masoudgb/Gost-ip6#5]
با درود فراوان خدمت دوست گرامی سوال بنده این است که حتما باید سرور داخل ایپی سیکس اختصاصی داشته باشد ؟! چوت سرور بنده ایپی فور ساپورت هست و هرچه به صورت لوکال و یا تانل بروکر ایپی 6 بهش تزریق کردم پینگ به ایپی سیکس خارجم نمیدهد و پیام ping connect: Network is unreachable میدهد چاره خاصی ندارد ؟؟ و دیتاسنتر بنده 6 ساپورت نیست با تشکر

**Comment by masoudgb** [comment]
عرض ادب متاسفانه بدون ایپی 6 سرور امکان پذیر نیست
