### ISSUE TITLE
ایپی جدید

### ISSUE THREAD

**Issue by Mohammadaminsdr** [masoudgb/Gost-ip6#50]
سلام وقت بخیر ایپی جدید که اضافه میکنیم انگار ست نمیشه پورت ها فرق میکنن و سرور اولی که میزنیم کار میکنه ولی تو اضافه کردن سرور جدید اتصال برقرار نمیشه

**Comment by masoudgb** [comment]
> سلام وقت بخیر ایپی جدید که اضافه میکنیم انگار ست نمیشه پورت ها فرق میکنن و سرور اولی که میزنیم کار میکنه ولی تو اضافه کردن سرور جدید اتصال برقرار نمیشه

سلام وقت بخیر
لطفاً لاگ رو ارسال بفرمایید

**Comment by Mohammadaminsdr** [comment]
هر سری بعد زدن systemctl daemon-reload && systemctl restart gost_0 ایپی جدید که اضافه کردیم حذف میشه یعنی با گوست نمیشه یه ایران رو به چند تا خارج ت.انل زد ؟

**Comment by masoudgb** [comment]
> هر سری بعد زدن systemctl daemon-reload && systemctl restart gost_0 ایپی جدید که اضافه کردیم حذف میشه یعنی با گوست نمیشه یه ایران رو به چند تا خارج ت.انل زد ؟

از طریق گزینه add new ip اضافه بفرمایید

**Comment by Mohammadaminsdr** [comment]
از همون بخش اضافه میکنیم ولی سرور دوم پینگ نمیده با روش gre6 اونم

**Comment by masoudgb** [comment]
> از همون بخش اضافه میکنیم ولی سرور دوم پینگ نمیده با روش gre6 اونم

از ایپی 6 استاتیک سرور استفاده بفرمایید
