### ISSUE TITLE
2سرور خارج

### ISSUE THREAD

**Issue by AH919** [masoudgb/Gost-ip6#54]
سلام من دو سرور خارج دارم و پورت های مختلفی هستن چطوری میتونم با اسکریپت شما یه سری پورت رو فوروارد کنم به یه ایپی و یه سری پورت دیگه رو به ایپی دیگری

**Comment by AH919** [comment]
دیدم جوابش رو ممنون

**Comment by masoudgb** [comment]
> سلام من سرور یه مشکلی داره با ایپی 4 تانل میشه ولی با ایپی 6 نه چرا؟

درود وقت بخیر برای اضافه کردن آی‌پی‌های جدید از گزینه add new IP استفاده بفرمایید
