### ISSUE TITLE
عالی

### ISSUE THREAD

**Issue by imahdavii** [masoudgb/Gost-ip6#6]
سلام واقعا اسکریپتتون عالیه فقط سوالی داشتم در مورد این که میشه چنتا خارج رو اضافه کرد مثلا با کاما ایپی 6 هارو از هم جدا کنیم ولی پورت متفاوت؟

**Comment by masoudgb** [comment]
سپاسگزارم از لطف شما بله میتونید فایل گاست سرویس رو ویرایش بفرمایید

nano /usr/lib/systemd/system/gost.service

ExecStart=/usr/local/bin/gost -L=tcp://:port1/[ip1]:port1 -L=tcp://:port2/[ip1]:port2 -L=tcp://:port3/[ip2]:port3

طبق مثال بالا در انتهای لاین کامنت جدید رو وارد بفرمایید دقت کنید پورت تکراری نباشد.
البته ویژگی مولتی ایپی در آپدیت بعدی قرار خواهد گرفت
