### ISSUE TITLE
مشکل

### ISSUE THREAD

**Issue by Mahdi84S** [masoudgb/Gost-ip6#7]
درود ، وقت بخیر

تانلی که ساختید ،گزینه رنج پورت IPV6 کار نمیکنه
ممنون میشم درست کنید

**Comment by masoudgb** [comment]
وقت بخیر بزودی آپدیت میشه و باگ رنج پورت رفع میشه

**Comment by masoudgb** [comment]
باگ رنج ایپی رفع شد

**Comment by Mahdi84S** [comment]
درود
هنوز هم رنج آیپی ipv6 کار نمیکنه
