### ISSUE TITLE
اجرای اسکریپت 

### ISSUE THREAD

**Issue by milad97** [masoudgb/Gost-ip6#77]
سلام وقت بخیر 
از دیروز که ipv6 ها بستن اسکریپت اجرا نمیشه میدونم اسکریپت مشکلی نداره (با سرور خارج چک کردم ) اما با سرور ایران ارور میده وصل میشه راهی هست برای حل این مشکل با آسیاتک و 0-1 چک کردم

**Comment by milad97** [comment]
وقت بخیر 8.8.8.8 و 8.8.4.4 گزاشتم اما جواب نمیده dns خاصی رو باید بزنم ؟

**Comment by masoudgb** [comment]
> وقت بخیر 8.8.8.8 و 8.8.4.4 گزاشتم اما جواب نمیده dns خاصی رو باید بزنم ؟

بزودی لینک پروژه آپدیت میشه تا مشکل دانلود از گیت رفع بشه

**Comment by masoudgb** [comment]
> وقت بخیر 8.8.8.8 و 8.8.4.4 گزاشتم اما جواب نمیده dns خاصی رو باید بزنم ؟

لینک اسکریپت آپدیت شد
