### ISSUE TITLE
استفاده همزمان ipv4+ipv6

### ISSUE THREAD

**Issue by mohamadfajim** [masoudgb/Gost-ip6#8]
سلامعزیز وقتت بخیر

امکان تانل ghost همزمان هم ipv4 هم ipv6 روی یک سرور وجود داره که مثل لود بابانسر عمل کنه ؟

بعضی موقع ها یکیش به اختلال میخوره از اون یکی استفاده کنه

اگر امکانش نیست میتونید با هزینه برام این مورد به صورت شخصی بنویسید؟
تشکر

**Comment by masoudgb** [comment]
درود وقت بخیر 
مشکلی برای استفاده همزمان از ایپی 4 و 6 نیست اما نمی‌توانید از پورت یکسان استفاده بفرمایید.
برای این منظور ابتدا یکی از گزینه های 4 یا 6 را انتخاب کنید در پایان مجدد امکان اضافه کردن ایپی جدید را خواهید داشت
