### ISSUE TITLE
fb

### ISSUE THREAD

**Issue by alizshfe** [masoudgb/Gost-ip6#9]
سلام.من با  ipv6 تانل ایجاد کردم  اندروید همه چی وصل هست کاملا عالی کار می کند ولی توی آیفون یا از طریق کروم سایت هایی مثل x فیسبوک یا اپ واتساپ کار نمی کنه.
پنل من سنایی هست .
می خواستم بدونم نظری دارید.
ممنون

**Comment by masoudgb** [comment]
درود روز بخیر سرور ایران شما ایپی 6 داشت یا لوکال ایجاد کردید.؟

**Comment by alizshfe** [comment]
داره خودش
